
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "KgmWebService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:/D:/pms.xml")
public class KgmWebService
    extends Service
{

    private final static URL KGMWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException KGMWEBSERVICE_EXCEPTION;
    private final static QName KGMWEBSERVICE_QNAME = new QName("http://tempuri.org/", "KgmWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/pms.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KGMWEBSERVICE_WSDL_LOCATION = url;
        KGMWEBSERVICE_EXCEPTION = e;
    }

    public KgmWebService() {
        super(__getWsdlLocation(), KGMWEBSERVICE_QNAME);
    }

    public KgmWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), KGMWEBSERVICE_QNAME, features);
    }

    public KgmWebService(URL wsdlLocation) {
        super(wsdlLocation, KGMWEBSERVICE_QNAME);
    }

    public KgmWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KGMWEBSERVICE_QNAME, features);
    }

    public KgmWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KgmWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
    
    /**
     * 
     * @return
     *     returns KgmWebServiceSoap
     */
    @WebEndpoint(name = "KgmWebServiceSoap")
    public KgmWebServiceSoap getKgmWebServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "KgmWebServiceSoap"), KgmWebServiceSoap.class);
    }
    
    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KgmWebServiceSoap
     */
    @WebEndpoint(name = "KgmWebServiceSoap")
    public KgmWebServiceSoap getKgmWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "KgmWebServiceSoap"), KgmWebServiceSoap.class, features);
    }
    
    /**
     * 
     * @return
     *     returns KgmWebServiceSoap
     */
    @WebEndpoint(name = "KgmWebServiceSoap12")
    public KgmWebServiceSoap getKgmWebServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "KgmWebServiceSoap12"), KgmWebServiceSoap.class);
    }
    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KgmWebServiceSoap
     */
    @WebEndpoint(name = "KgmWebServiceSoap12")
    public KgmWebServiceSoap getKgmWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "KgmWebServiceSoap12"), KgmWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KGMWEBSERVICE_EXCEPTION!= null) {
            throw KGMWEBSERVICE_EXCEPTION;
        }
        return KGMWEBSERVICE_WSDL_LOCATION;
    }
    
}
