
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KgmWebServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KgmWebServiceSoap {


    /**
     * ≤‚ ‘¡¨Ω”
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConnectionTest", action = "http://tempuri.org/ConnectionTest")
    @WebResult(name = "ConnectionTestResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConnectionTest", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConnectionTest")
    @ResponseWrapper(localName = "ConnectionTestResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConnectionTestResponse")
    public String connectionTest();

    /**
     * 
     * @param macAddress
     * @param printSettings
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PrintLabel", action = "http://tempuri.org/PrintLabel")
    @WebResult(name = "PrintLabelResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PrintLabel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintLabel")
    @ResponseWrapper(localName = "PrintLabelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintLabelResponse")
    public String printLabel(
        @WebParam(name = "macAddress", targetNamespace = "http://tempuri.org/")
        String macAddress,
        @WebParam(name = "printSettings", targetNamespace = "http://tempuri.org/")
        String printSettings);

}
